version: '2'
services:
   socketio:
    build:
      context: ./socket/
      dockerfile: Dockerfile
    ports:
     - "3003:3003"
    restart: always
   webapp:
     build:
      context: ./
      dockerfile: Dockerfile
     restart: always
   nginx:
     links: 
       - webapp
     build:
      context: ./nginx/
      dockerfile: Dockerfile
     ports:
      - "80:80"
     restart: always 

