version: '2'
services:
   socketio:
    build:
      context: ./socket/
      dockerfile: Dockerfile
    depends_on:
      - fluentd
      - elasticsearch
    links:
     - fluentd
    ports:
     - "3004:3004"
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentd:24224"
    restart: always
   webapp:
     build:
      context: ./
      dockerfile: Dockerfile
     restart: always
   nginx:
     links: 
       - webapp
     build:
      context: ./nginx/
      dockerfile: Dockerfile
     ports:
      - "80:80"
     restart: always 
   fluentd:
     image: fluent/fluentd:ubuntu-base
     links: 
       - elasticsearch
     volumes:
      - ./fluentd/etc/fluentd.conf:/fluentd/etc/fluent.conf
      - ./fluentd/etc/start.sh:/fluentd/etc/start.sh
     command: /fluentd/etc/start.sh
   elasticsearch:
     build:
      context: ./elasticsearch/
      dockerfile: Dockerfile
     volumes:
       - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
   kibana:
     build:
      context: ./kibana/
      dockerfile: Dockerfile
     links:
       - elasticsearch
     restart: always
     ports:
       - "5601:5601"
     environment:
       - ELASTICSEARCH_URL=http://elasticsearch:9200
