apiVersion: v1
data:
  config.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - localhost:9090

      - job_name: statsd-exporter
        scrape_interval: 30s
        metrics_path: "/metrics"
        static_configs:
          - targets: ["statsd-exporter.default.svc.cluster.local:9102"]
            labels:
              kubernetes_pod_name: 'statsd-exporter'
              kubernetes_namespace: 'default'

kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
