---
apiVersion: v1
data:
  config.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - localhost:9090

      - job_name: statsd-exporter
        scrape_interval: 30s
        metrics_path: "/metrics"
        static_configs:
          - targets: ["statsd-exporter.default.svc.cluster.local:9102"]
            labels:
              kubernetes_pod_name: 'statsd-exporter'
              kubernetes_namespace: 'default'

kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
---
apiVersion: v1
data:
  default.conf: |-
    server {
        listen       80;
        server_name  localhost;


        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
        location /data {
          proxy_pass      http://127.0.0.1:9000;
        }

    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-02-21T01:54:41Z"
  name: frontend-conf
  namespace: default
