apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: statsd-exporter
  name: statsd-exporter
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: statsd-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: statsd-exporter
    spec:
      containers:
        - args:
            - --statsd.mapping-config=/opt/statsd_mapping.conf
          image: prom/statsd-exporter
          imagePullPolicy: IfNotPresent
          name: statsd-exporter
          ports:
            - containerPort: 9102
              protocol: TCP
            - containerPort: 9125
              protocol: UDP
          resources:
            requests:
              cpu: "0"
              memory: "0"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/
              name: config
      volumes:
        - configMap:
            defaultMode: 420
            name: statsd-exporter
          name: config
