apiVersion: v1
kind: Service
metadata:
  labels:
    app: statsd-exporter
  name: statsd-exporter
  namespace: default
spec:
  ports:
    - name: statsd
      port: 9125
      protocol: UDP
      targetPort: 9125
    - name: prom
      port: 9102
      protocol: TCP
      targetPort: 9102
  selector:
    app: statsd-exporter
  sessionAffinity: None
  type: ClusterIP
