apiVersion: v1
data:
  config.yaml: |
    rules:
    - seriesQuery: 'mystats_rum_rt_load'
      resources:
        overrides:
          kubernetes_namespace: {resource: "namespace"}
          kubernetes_pod_name: {resource: "service"}
      metricsQuery: 'avg(avg_over_time(<<.Series>>{quantile="0.99"}[1m])) by (<<.GroupBy>>)'
kind: ConfigMap
metadata:
  labels:
    app: prometheus-adapter
  name: prom-adapter-prometheus-adapter
  namespace: default
